name: universal_file_viewer
description: "A Flutter package to preview images, videos, PDFs, Word, Excel, CSV, PPT, and more."
version: 0.1.2
homepage: https://github.com/Shonu72/
repository: https://github.com/Shonu72/universal_file_viewer

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter

  open_file: ^3.5.10
  video_player: ^2.9.5
  pdfrx: ^1.1.29
  excel: #^4.0.6
    git:
      url: https://github.com/upbase-io/excel
      ref: main
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^4.0.7
  xml: ^6.5.0
  markdown: ^7.3.0
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4
  shimmer: ^3.0.0
  docx_file_viewer: #^0.0.7
    git:
      url: https://github.com/upbase-io/docx_viewer
      ref: main

  ### in the near future use in case the docX owner do not merge I'll create the lib for the mean time I put the code in the word file preview
  ###     #git:
  #    #  url: https://github.com/oscarshaitan/docx_viewer
  #    #  ref: 6356e9133f41cc56205d8da0e02c3ebb94440f25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - filepreviewer
  - widgets
  - package
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

